-- MySQL Script generated by MySQL Workbench
-- Sat Feb 12 02:53:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dsistaj
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dsistaj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dsistaj` DEFAULT CHARACTER SET utf8 ;
USE `dsistaj` ;

-- -----------------------------------------------------
-- Table `dsistaj`.`araclar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsistaj`.`araclar` (
  `arac_ID`  NOT NULL,
  `plaka` VARCHAR(45) NOT NULL,
  `kurulus` VARCHAR(45) NOT NULL,
  `arac_model` VARCHAR(45) NOT NULL,
  `arac_km_giris`  NULL DEFAULT NULL,
  `arac_km_cikis`  NULL DEFAULT NULL,
  PRIMARY KEY (`arac_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dsistaj`.`gidilecek_yerler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsistaj`.`gidilecek_yerler` (
  `yer_ID`  NOT NULL,
  `adres` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`yer_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 278
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dsistaj`.`personel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsistaj`.`personel` (
  `p_ID`  NOT NULL,
  `p_ad_soyad` VARCHAR(45) NOT NULL,
  `p_unvan` VARCHAR(45) NOT NULL,
  `birim_ID`  NOT NULL,
  `sifre` VARCHAR(45) NOT NULL,
  `kullanici_adi` VARCHAR(45) NOT NULL,
  `amirpersonel_ID`  NULL DEFAULT NULL,
  PRIMARY KEY (`p_ID`),
  UNIQUE INDEX `kullanici_adi_UNIQUE` (`kullanici_adi` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dsistaj`.`soforler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsistaj`.`soforler` (
  `surucu_ID`  NOT NULL,
  `surucu_ad_soyad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`surucu_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dsistaj`.`gorev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dsistaj`.`gorev` (
  `gorev_ID`  NOT NULL,
  `personel_ID`  NOT NULL,
  `bamir_ID`  NULL DEFAULT NULL,
  `bsofor_ID`  NULL DEFAULT NULL,
  `tarih_saat`  NOT NULL,
  `yer_ID`  NULL DEFAULT NULL,
  `arac_ID`  NULL DEFAULT NULL,
  `sofor_ID`  NULL DEFAULT NULL,
  `bamir_onay`  NULL DEFAULT NULL,
  `bsofor_onay`  NULL DEFAULT NULL,
  PRIMARY KEY (`gorev_ID`),
  INDEX `fk_gorev_gidilecek_yerler_idx` (`yer_ID` ASC) VISIBLE,
  INDEX `fk_gorev_soforler_idx` (`sofor_ID` ASC) VISIBLE,
  INDEX `fk_gorev_araclar_idx` (`arac_ID` ASC) VISIBLE,
  INDEX `fk_gorev_personel_idx` (`personel_ID` ASC) VISIBLE,
  CONSTRAINT `fk_gorev_araclar`
    FOREIGN KEY (`arac_ID`)
    REFERENCES `dsistaj`.`araclar` (`arac_ID`),
  CONSTRAINT `fk_gorev_gidilecek_yerler`
    FOREIGN KEY (`yer_ID`)
    REFERENCES `dsistaj`.`gidilecek_yerler` (`yer_ID`),
  CONSTRAINT `fk_gorev_personel`
    FOREIGN KEY (`personel_ID`)
    REFERENCES `dsistaj`.`personel` (`p_ID`),
  CONSTRAINT `fk_gorev_soforler`
    FOREIGN KEY (`sofor_ID`)
    REFERENCES `dsistaj`.`soforler` (`surucu_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
